### ISSUE TITLE
Using pre-built images

### ISSUE THREAD

**Issue by fxlrnrpt** [neomag/tun2socks#1]
Спасибо за идею! У меня в коненом итоге завелось в оригинальным tun2socks докер образом.

```
version: "3.7"
services:
  tun2vless:
    image: ghcr.io/xjasonlyu/tun2socks:v2.5.2
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - PROXY=$PROXY
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    restart: always
    container_name: tun2vless
    hostname: tun2vless
    extra_hosts:
      - host.docker.internal:host-gateway
  payload:
    image: whatever
    restart: always
    network_mode: service:tun2vless
```

P.S. Просто FYI если кто-то еще найде эту репу в гугле
